export const countryToDomain = {
  // USA
  "United States": "us",

  // Canada
  "Canada": "canada",

  // Latin America
  "Mexico": "latin",
  "Brazil": "latin",
  "Argentina": "latin",
  "Chile": "latin",
  "Colombia": "latin",
  "Peru": "latin",
  "Ecuador": "latin",
  "Uruguay": "latin",
  "Paraguay": "latin",
  "Bolivia": "latin",
  "Venezuela": "latin",
  "Costa Rica": "latin",
  "Panama": "latin",
  "Guatemala": "latin",
  "Honduras": "latin",
  "El Salvador": "latin",
  "Nicaragua": "latin",
  "Dominican Republic": "latin",
  "Cuba": "latin",

  // Europe
  "United Kingdom": "europe",
  "Germany": "europe",
  "France": "europe",
  "Italy": "europe",
  "Spain": "europe",
  "Portugal": "europe",
  "Netherlands": "europe",
  "Belgium": "europe",
  "Luxembourg": "europe",
  "Ireland": "europe",
  "Austria": "europe",
  "Switzerland": "europe",
  "Sweden": "europe",
  "Norway": "europe",
  "Denmark": "europe",
  "Finland": "europe",
  "Poland": "europe",
  "Czech Republic": "europe",
  "Slovakia": "europe",
  "Hungary": "europe",
  "Romania": "europe",
  "Bulgaria": "europe",
  "Croatia": "europe",
  "Slovenia": "europe",
  "Estonia": "europe",
  "Latvia": "europe",
  "Lithuania": "europe",
  "Greece": "europe",
  "Malta": "europe",
  "Iceland": "europe",
  "Bosnia and Herzegovina": "europe",
  "Montenegro": "europe",
  "North Macedonia": "europe",
  "Albania": "europe",

  // APAC
  "China": "apac",
  "Japan": "apac",
  "South Korea": "apac",
  "Singapore": "apac",
  "Malaysia": "apac",
  "Thailand": "apac",
  "Indonesia": "apac",
  "Vietnam": "apac",
  "Philippines": "apac",
  "Australia": "apac",
  "Hong Kong": "apac",
  "Taiwan": "apac",
  
};